apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-shop-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    volumeSize: 10
