apiVersion: v1
kind: Service
metadata:
  name: aws-shop-service
  labels:
    app: aws-shop
spec:
  selector:
    app: aws-shop
  ports:
    - name         : aws-shop-listener
      protocol     : TCP
      port         : 1234
      targetPort   : 8080
  type: LoadBalancer
